Feature/GitHub actions
LLNL/sundials pull request #152
Opened 2022-06-07 22:49 UTC by balos1

2022-06-14 03:10 UTC, drreynolds approved these changes
Aside from the incredibly minor comments I made, this looks excellent to me.

2022-06-14 03:10 UTC, drreynolds commented on doc/sundials_developers/source/testing/Local.rst
> +same steps above apply. using ``podman`` instead of ``docker``). Podman is
Extraneous period

2022-06-14 03:10 UTC, drreynolds commented on docker/sundials-ci/int64-single/spack.yaml
> +  # - petsc~double+int64 ^openblas+ilp64 %gcc@9.4.0 arch=x86_64
Should these lines be removed instead of commented out?

2022-06-14 19:55 UTC, balos1 commented on src/sundials/sundials_math.c
> +long double SUNNextafterld(long double from, long double to)
No they are not, I added them for the sake of completeness, but I suppose we can drop the extra ones.

2022-06-14 19:56 UTC, balos1 commented on src/sundials/sundials_math.c
> +  return (sunrealtype) SUNNextafterld(val, -0.0);
Should be using it here, I think it was a copy-paste error.

2022-06-17 22:23 UTC, balos1 commented on src/sundials/sundials_math.c
> +#if (__STDC_VERSION__ >= 199901L)
Yes, we should. I will take care of this after the core problem is fixed with #156.

2022-06-21 20:13 UTC, gardner48 requested changes
One minor comment on the recent updates and there are a few unresolved minor comments from my earlier review.

2022-06-22 18:58 UTC, balos1 commented on doc/sundials_developers/source/testing/Local.rst
> +`https://hub.docker.com/r/balos1/sundials-ci <https://hub.docker.com/r/balos1/sundials-ci>_`
As per offline discussion, we will use the GitHub container registry instead.

2022-06-22 19:03 UTC, balos1 commented on test/test_driver.sh
> +# fi
yep

2022-06-23 23:51 UTC, gardner48 requested changes
Super minor updates, otherwise LGTM

2022-06-23 23:51 UTC, gardner48 commented on doc/shared/versions.py
> +year = '2022'
New line at end of file

2022-06-23 23:51 UTC, gardner48 commented on doc/superbuild/source/conf.py
> +.. |YEAR| replace:: 2022
```suggestion
.. |YEAR| replace:: {year}
```

2022-06-23 23:51 UTC, gardner48 commented on docker/sundials-ci/build-all-containers.sh
> +docker build -t ghcr.io/llnl/sundials-ci-${image}:spack-develop --build-arg spack_yaml="${image}/spack.yaml" spack-nightly/
New line at end of file

2022-06-24 15:52 UTC, gardner48 approved these changes

2022-06-24 16:14 UTC, merged