GetUserData functions
LLNL/sundials pull request #159
Opened 2022-06-14 01:14 UTC by gardner48

* Add `GetUserData` functions to each package

2022-06-14 02:44 UTC, drreynolds commented on doc/arkode/guide/source/Usage/ARKStep_c_interface/User_callable.rst
> +      * *user_data* -- pointer to a user data pointer.
Would this read more clearly as "memory reference to a user data pointer"?

2022-06-14 02:44 UTC, drreynolds commented on doc/arkode/guide/source/Usage/ERKStep_c_interface/User_callable.rst
> +      * *user_data* -- pointer to a user data pointer.
Would this read more clearly as "memory reference to a user data pointer"?

2022-06-14 02:45 UTC, drreynolds commented on doc/arkode/guide/source/Usage/MRIStep_c_interface/User_callable.rst
> +   * *user_data* -- pointer to a user data pointer.
Would this read more clearly as "memory reference to a user data pointer"?

2022-06-14 02:45 UTC, drreynolds commented on doc/cvode/guide/source/Usage/index.rst
> +     * ``user_data`` -- pointer to the user data pointer.
Would this read more clearly as "memory reference to a user data pointer"?

2022-06-14 02:45 UTC, drreynolds commented on doc/cvodes/guide/source/Usage/SIM.rst
> +     * ``user_data`` -- pointer to the user data pointer.
Would this read more clearly as "memory reference to a user data pointer"?

2022-06-14 02:46 UTC, drreynolds commented on doc/ida/guide/source/Usage/index.rst
> +     * ``user_data`` -- pointer to the user data pointer.
Would this read more clearly as "memory reference to a user data pointer"?

2022-06-14 02:46 UTC, drreynolds commented on doc/idas/guide/source/Usage/SIM.rst
> +     * ``user_data`` -- pointer to the user data pointer.
Would this read more clearly as "memory reference to a user data pointer"?

2022-06-14 02:47 UTC, drreynolds commented on doc/kinsol/guide/source/Usage/index.rst
> +     * ``user_data`` -- pointer to the user data pointer.
Would this read more clearly as "memory reference to a user data pointer"?

2022-06-14 02:58 UTC, drreynolds requested changes
A few minor changes are needed, along with some suggested documentation phrasing changes (not required).

2022-06-14 02:58 UTC, drreynolds commented on include/idas/idas.h
> +SUNDIALS_EXPORT int IDAGetUserData(void *cvode_mem, void** user_data);
Should be `void *ida_mem`

2022-06-14 02:58 UTC, drreynolds commented on include/ida/ida.h
> +SUNDIALS_EXPORT int IDAGetUserData(void *cvode_mem, void** user_data);
Should be `void *ida_mem`

2022-06-14 02:58 UTC, drreynolds commented on include/kinsol/kinsol.h
> +SUNDIALS_EXPORT int KINGetUserData(void *cvode_mem, void** user_data);
Should be `void *kinmem`

2022-06-14 02:58 UTC, drreynolds commented on src/arkode/arkode_io.c
> +    arkProcessError(NULL, ARK_MEM_NULL, "ARKode",
Should be "ARKODE"

2022-06-14 02:58 UTC, drreynolds commented on src/idas/idas_io.c
> +    IDAProcessError(NULL, IDA_MEM_NULL, "IDASs", "IDAGetUserData", MSG_NO_MEM);
Should be "IDAS"

2022-06-14 02:58 UTC, drreynolds commented on test/unit_tests/arkode/C_serial/ark_test_getuserdata.c
> +  retval = ARKStepSetUserData(arkode_mem, &udata_in);
This should call `MRIStepSetUserData()`

2022-06-14 02:58 UTC, drreynolds commented on test/unit_tests/arkode/C_serial/ark_test_getuserdata.c
> +  retval = ARKStepGetUserData(arkode_mem, &udata_out);
This should call `MRIStepGetUserData()`

2022-06-17 18:11 UTC, balos1 approved these changes

2022-06-17 18:11 UTC, merged