Update sundials citations
LLNL/sundials pull request #162
Opened 2022-06-22 03:44 UTC by gardner48

* Add citation for "Enabling new flexibility in the SUNDIALS suite of nonlinear and differential/algebraic equation solvers"
* Add citation for "ARKODE: A flexible IVP solver infrastructure for one-step methods"

2022-06-22 12:55 UTC, drreynolds submitted a review, later dismissed

2022-06-22 18:41 UTC, cswoodward approved these changes

2022-06-22 18:47 UTC, balos1 requested changes

2022-06-22 18:47 UTC, balos1 commented on CITATIONS.md
>  @article{hindmarsh2005sundials,
Put the new TOMS paper first

2022-06-22 18:47 UTC, balos1 commented on doc/shared/cite_sundials.rst
> +   @article{hindmarsh2005sundials,
Put the new TOMS paper first

2022-06-22 19:48 UTC, gardner48 commented
I've updated the ordering so the new TOMS paper is listed first.

2022-06-22 19:56 UTC, drreynolds approved these changes

2022-06-23 16:22 UTC, balos1 approved these changes

2022-06-24 20:47 UTC, merged