Fix floating-point underflow during root finding in cvode and arkode
LLNL/sundials pull request #230
Opened 2022-11-25 10:58 UTC by avandecreme

This is a PR cherry picking https://github.com/novadiscovery/sundials/commit/f7a725e9964a4177b6055a972ff25fea48c404f0 to fix issue #57

2022-11-26 19:44 UTC, drreynolds requested changes
I think that these changes are great.  However, I have some additional requests before this contribution can be accepted:
1. Please add a sentence to the top-level `CHANGELOG.md` indicating the fix.  Also add a similar comment to the "Changes from previous versions" section in both the files `doc/arkode/guide/source/Introduction.rst` and `doc/cvode/guide/source/Introduction.rst`.
2. Request to merge the PR into the `develop` branch of the main SUNDIALS repository (not `main`)

2022-11-28 07:41 UTC, avandecreme commented
> I think that these changes are great. However, I have some additional requests before this contribution can be accepted:
> 
>     1. Please add a sentence to the top-level `CHANGELOG.md` indicating the fix.  Also add a similar comment to the "Changes from previous versions" section in both the files `doc/arkode/guide/source/Introduction.rst` and `doc/cvode/guide/source/Introduction.rst`.
> 
>     2. Request to merge the PR into the `develop` branch of the main SUNDIALS repository (not `main`)

Thanks for reviewing. I did the changes you asked and assumed the next version would be 6.4.2 but let me know if I should put something else.

2022-11-28 14:33 UTC, drreynolds commented on doc/arkode/guide/source/Introduction.rst
> +Changes in v6.4.2
```suggestion
Changes in v5.4.2
```

2022-11-28 15:35 UTC, drreynolds submitted a review, later dismissed

2022-11-28 16:14 UTC, balos1 submitted a review, later dismissed
LGTM

2022-11-28 17:42 UTC, balos1 commented
@gardner48 has pointed out offline that we will want to make this change in the other integrator packages as well.

2022-11-29 14:22 UTC, drreynolds approved these changes

2022-11-29 16:27 UTC, balos1 submitted a review, later dismissed

2022-11-29 19:04 UTC, balos1 commented
Thanks for this @avandecreme, it is very appreciated. One last request, could you please sign the commit as indicated at the bottom of the [contributing guide](https://github.com/LLNL/sundials/blob/main/CONTRIBUTING.md)?

2022-11-29 21:49 UTC, gardner48 submitted a review, later dismissed

2022-11-30 07:40 UTC, avandecreme commented
Signed-off added.

2022-11-30 13:43 UTC, drreynolds approved these changes

2022-11-30 20:51 UTC, gardner48 approved these changes

2022-11-30 20:52 UTC, merged