Fix link on non-Linux
LLNL/sundials pull request #243
Opened 2022-12-25 21:29 UTC by sthibaul

With at least version 3.25.1 of cmake, the link line of the test_nvector_pthreads ends up so:

/usr/bin/cc -fcommon -Wl,-z,relro -Wl,-z,now CMakeFiles/test_nvector_pthreads.dir/test_nvector_pthreads.c.o ../CMakeFiles/test_nvector_obj.dir/test_nvector.c.o -o test_nvector_pthreads  -Wl,-rpath,/<<PKGBUILDDIR>>/debian/build/src/nvector/pthreads/fmod:/<<PKGBUILDDIR>>/debian/build/src/nvector/serial:/<<PKGBUILDDIR>>/debian/build/src/nvector/pthreads ../../../src/nvector/pthreads/fmod/libsundials_fnvecpthreads_mod.so.6.4.1 -lm -lpthread ../../../src/nvector/serial/libsundials_nvecserial.so.6.4.1 ../../../src/nvector/pthreads/libsundials_nvecpthreads.so.6.4.1

but that fails to link with:

/usr/bin/ld: ../../../src/nvector/pthreads/libsundials_nvecpthreads.so.6.4.1: undefined reference to `pthread_create' /usr/bin/ld: ../../../src/nvector/pthreads/libsundials_nvecpthreads.so.6.4.1: undefined reference to `pthread_join'

because since -lpthread is before libsundials_nvecpthreads.so.6.4.1 in the link line, the "as-needed" link optimization ignores -lpthread.

Anyway, libsundials_nvecpthreads should be already linking against libpthread, and not have its user have to determine that they should use -lpthread. This is what this commit does, thus fixing building sundials on non-Linux entirely (on Linux, glibc has moved all pthread symbols into libc so the problem doesn't appear there any more)

2022-12-27 06:30 UTC, balos1 requested changes
Hi @sthibaul, thanks for the PR. It would be preferable to link to the `Threads::Threads` target instead of `${CMAKE_THREAD_LIBS_INIT}` otherwise this change looks good to me. 

Please target the `develop` branch instead of `main`. Also, please review the [contributing guidelines](https://github.com/LLNL/sundials/blob/main/CONTRIBUTING.md) and sign the commit as shown in there.

2022-12-27 06:30 UTC, balos1 commented on src/nvector/pthreads/CMakeLists.txt
> +    PRIVATE ${CMAKE_THREAD_LIBS_INIT}
```suggestion
    PRIVATE Threads::Threads
```

2022-12-27 21:31 UTC, sthibaul commented on src/nvector/pthreads/CMakeLists.txt
> +    PRIVATE ${CMAKE_THREAD_LIBS_INIT}
That works too indeed, done so

2022-12-30 00:22 UTC, balos1 approved these changes

2022-12-30 00:23 UTC, balos1 submitted a review, later dismissed

2023-01-03 17:44 UTC, balos1 commented
@sthibaul Can you please sign the commit as shown here: https://github.com/LLNL/sundials/blob/main/CONTRIBUTING.md?

Thanks!

2023-01-03 17:57 UTC, sthibaul commented
Done so

2023-01-03 17:59 UTC, drreynolds approved these changes

2023-01-06 05:05 UTC, merged