Feature/sundialsfileopen
LLNL/sundials pull request #284
Opened 2023-06-12 20:28 UTC by drreynolds

Minor updates to two F2003 utility routines so that they can properly handle `stdout` and `stderr`.

While this is not tested in our current codes, this will be included in examples later  this summer (I tested it already).

2023-06-12 20:49 UTC, drreynolds commented
It's unclear to me why GitHub "cancelled" the single precision build and test of this PR.

2023-06-12 22:28 UTC, gardner48 requested changes
Looks good, I think all that's needed is to update the documentation for `SUNDIALSFileOpen` in `doc/shared/sundials/Fortran.rst` to note "There are two special filenames: stdout and stderr. These two filenames will result in output going to the standard output file and standard error file."

2023-06-13 02:09 UTC, drreynolds commented on src/sundials/sundials_futils.c
Yep, I forgot an #include (that seemed to complain, but not error, on my computer).

2023-06-13 05:24 UTC, gardner48 approved these changes

2023-06-13 20:34 UTC, balos1 approved these changes

2023-06-13 20:34 UTC, merged