tstop-copy
LLNL/sundials pull request #292
Opened 2023-06-22 18:01 UTC by drreynolds

Changed default 'tstop' behavior of ARKODE and CVODE(S) to copy the internal solution instead of performing interpolation.

2023-06-22 23:45 UTC, balos1 requested changes

2023-06-23 02:04 UTC, drreynolds commented on include/arkode/arkode_arkstep.h
> +SUNDIALS_EXPORT int ARKStepInterpolateStopTime(void *arkode_mem,
I thought that at first, but the very next function is `ARKStepClearStopTime` (similar in all other integrators), and not `ARKStepSetClearStopTime`, which already breaks the convention.

2023-06-23 02:57 UTC, gardner48 commented on include/arkode/arkode_arkstep.h
> +SUNDIALS_EXPORT int ARKStepInterpolateStopTime(void *arkode_mem,
The `ClearStopTime` functions are atypical as they don't set an option value that persists but instead perform a one time action. For this function I think `SetInterpolateStopTime` is preferable.

2023-06-27 15:55 UTC, balos1 approved these changes

2023-07-02 03:32 UTC, balos1 approved these changes

2023-07-06 15:43 UTC, merged

2023-07-06 15:59 UTC, gardner48 commented
I'm late to the party but LGTM