Example guide CVODE update (currently without Deep Dive)
LLNL/sundials pull request #309
Opened 2023-07-24 21:54 UTC by danmm16

Added example documentation in RestructuredText for CVODE. Complete aside from the deep dive that was promised.

2023-07-25 21:33 UTC, balos1 requested changes
Does this PR include documentation that refers to new examples that will come in PR #302?

2023-07-25 21:33 UTC, balos1 commented on danmm.lnk
This file should be removed

2023-07-25 21:33 UTC, balos1 commented on doc/cvode/examples/source/_templates/layout.html
The `_templates` and `_themes` directories need to be removed (they should not be committed).

2023-07-25 22:03 UTC, balos1 commented on doc/cvode/examples/source/conf.py
Ah, I see this is using the old Bootstrap theme. I will update it to use the readthedocs theme. This explains why `_templates` and `_themes` were committed.

2023-11-17 18:25 UTC, drreynolds commented
I'm closing this PR, since it includes many changes that are *not* relegated to only `doc/cvode`.  I'll reopen a different PR that includes only the relevant documentation changes.

2023-11-17 18:25 UTC, closed without merging