Feature/new tables
LLNL/sundials pull request #359
Opened 2023-10-27 15:26 UTC by drreynolds

Steven and I added some additional embedded explicit Runge--Kutta methods to ARKODE.

2023-10-27 17:49 UTC, gardner48 requested changes

2023-10-27 18:22 UTC, gardner48 commented
The single precision builds are currently failing with the errors below. I assume the actual table values are within the single precision range and just the rational expressions have constants that are not. Should we note this in the documentation? I'll update some of the CI testing flags shortly.
```
/var/lib/jenkins/workspace/SUNDIALS_GitHub_Test_PR-359/test/tarballs/sundials-6.6.1/src/arkode/arkode_butcher_erk.def:673:1: error: floating constant exceeds range of 'float' [-Werror=overflow]
 ARK_BUTCHER_TABLE(ARKODE_VERNER_9_5_6, { /* Verner-6-5b (DOI: 10.1007/s11075-009-9290-3) */
 ^
/var/lib/jenkins/workspace/SUNDIALS_GitHub_Test_PR-359/test/tarballs/sundials-6.6.1/src/arkode/arkode_butcher_erk.def:733:1: error: floating constant exceeds range of 'float' [-Werror=overflow]
 ARK_BUTCHER_TABLE(ARKODE_VERNER_10_6_7, { /* Verner-7-6 (DOI: 10.1007/s11075-009-9290-3) */
 ^
/var/lib/jenkins/workspace/SUNDIALS_GitHub_Test_PR-359/test/tarballs/sundials-6.6.1/src/arkode/arkode_butcher_erk.def:802:1: error: floating constant exceeds range of 'float' [-Werror=overflow]
 ARK_BUTCHER_TABLE(ARKODE_VERNER_13_7_8, { /* Verner-8-7 (DOI: 10.1007/s11075-009-9290-3) */
```

2023-10-27 18:41 UTC, drreynolds commented on doc/arkode/guide/source/Butcher.rst
> +   region is outlined in red; the embedding's region is in blue dashed.
The current stability region plotting script in our `analysis_utilities` repository colors them this way.  I can update the colors in that script and regenerate the plots, if desired.

2023-10-27 18:45 UTC, drreynolds commented
> The single precision builds are currently failing with the errors below. I assume the actual table values are within the single precision range and just the rational expressions have constants that are not. Should we note this in the documentation? I'll update some of the CI testing flags shortly.
> 
> ```
> /var/lib/jenkins/workspace/SUNDIALS_GitHub_Test_PR-359/test/tarballs/sundials-6.6.1/src/arkode/arkode_butcher_erk.def:673:1: error: floating constant exceeds range of 'float' [-Werror=overflow]
>  ARK_BUTCHER_TABLE(ARKODE_VERNER_9_5_6, { /* Verner-6-5b (DOI: 10.1007/s11075-009-9290-3) */
>  ^
> /var/lib/jenkins/workspace/SUNDIALS_GitHub_Test_PR-359/test/tarballs/sundials-6.6.1/src/arkode/arkode_butcher_erk.def:733:1: error: floating constant exceeds range of 'float' [-Werror=overflow]
>  ARK_BUTCHER_TABLE(ARKODE_VERNER_10_6_7, { /* Verner-7-6 (DOI: 10.1007/s11075-009-9290-3) */
>  ^
> /var/lib/jenkins/workspace/SUNDIALS_GitHub_Test_PR-359/test/tarballs/sundials-6.6.1/src/arkode/arkode_butcher_erk.def:802:1: error: floating constant exceeds range of 'float' [-Werror=overflow]
>  ARK_BUTCHER_TABLE(ARKODE_VERNER_13_7_8, { /* Verner-8-7 (DOI: 10.1007/s11075-009-9290-3) */
> ```

I don't see why I can't comment in-line to this item, so I'm answering in a separate comment.

Yes, I think that the issue is that the coefficients are provided in rational form, with components that have a large number of digits.  I could try to convert these to 40-digit decimals to inhibit these warnings, but I'm uncertain how to do this in an automated way (i.e., without manually entering these into Matlab/Mathematica, converting, and pasting the result.

2023-10-27 21:40 UTC, balos1 approved these changes

2023-10-27 22:33 UTC, gardner48 submitted a review, later dismissed

2023-10-28 01:05 UTC, Steven-Roberts commented on CHANGELOG.md
> +Added the third order ERK method `ARKODE_SHU_OSHER_3_2_3` the fourth order
```suggestion
Added the third order ERK method `ARKODE_SHU_OSHER_3_2_3`, the fourth order
```

2023-10-28 15:53 UTC, gardner48 approved these changes

2023-10-28 23:59 UTC, merged