error handling in idas
LLNL/sundials pull request #384
Opened 2023-12-06 22:41 UTC by balos1

2023-12-07 05:00 UTC, drreynolds commented on src/idas/idaa.c
> +                      MSGAM_BAD_TINTERP);
```suggestion
                      MSGAM_BAD_TINTERP, tt);
```

2023-12-07 05:00 UTC, drreynolds commented on src/idas/idaa.c
> +                      MSGAM_BAD_TINTERP);
```suggestion
                      MSGAM_BAD_TINTERP, tt);
```

2023-12-07 05:03 UTC, drreynolds commented on src/idas/idas.c
> +                        MSG_BAD_TSTOP);
```suggestion
                        MSG_BAD_TSTOP, IDA_mem->ida_tstop, IDA_mem->ida_tn);
```

2023-12-07 05:03 UTC, drreynolds commented on src/idas/idas.c
> +                        MSG_RTFUNC_FAILED);
```suggestion
                        MSG_RTFUNC_FAILED, IDA_mem->ida_tn);
```

2023-12-07 05:03 UTC, drreynolds commented on src/idas/idas.c
> +                        MSG_CLOSE_ROOTS);
```suggestion
                        MSG_CLOSE_ROOTS, IDA_mem->ida_tlo);
```

2023-12-07 05:03 UTC, drreynolds commented on src/idas/idas.c
> +                        MSG_RTFUNC_FAILED);
```suggestion
                        MSG_RTFUNC_FAILED, IDA_mem->ida_tlo);
```

2023-12-07 05:04 UTC, drreynolds commented on src/idas/idas.c
> +                          __FILE__, MSG_RTFUNC_FAILED);
```suggestion
                          __FILE__, MSG_RTFUNC_FAILED, IDA_mem->ida_tlo);
```

2023-12-07 05:04 UTC, drreynolds commented on src/idas/idas.c
> +                      MSG_MAX_STEPS);
```suggestion
                      MSG_MAX_STEPS, IDA_mem->ida_tn);
```

2023-12-07 05:04 UTC, drreynolds commented on src/idas/idas.c
> +                          MSG_EWT_NOW_FAIL);
```suggestion
                          MSG_EWT_NOW_FAIL, IDA_mem->ida_tn);
```

2023-12-07 05:04 UTC, drreynolds commented on src/idas/idas.c
> +                          MSG_EWT_NOW_BAD);
```suggestion
                          MSG_EWT_NOW_BAD, IDA_mem->ida_tn);
```

2023-12-07 05:05 UTC, drreynolds commented on src/idas/idas.c
> +                          MSG_EWTQ_NOW_BAD);
```suggestion
                          MSG_EWTQ_NOW_BAD, IDA_mem->ida_tn);
```

2023-12-07 05:05 UTC, drreynolds commented on src/idas/idas.c
> +                          MSG_EWTS_NOW_BAD);
```suggestion
                          MSG_EWTS_NOW_BAD, IDA_mem->ida_tn);
```

2023-12-07 05:05 UTC, drreynolds commented on src/idas/idas.c
> +                          MSG_EWTQS_NOW_BAD);
```suggestion
                          MSG_EWTQS_NOW_BAD, IDA_mem->ida_tn);
```

2023-12-07 05:05 UTC, drreynolds commented on src/idas/idas.c
> +                      MSG_TOO_MUCH_ACC);
```suggestion
                      MSG_TOO_MUCH_ACC, IDA_mem->ida_tn);
```

2023-12-07 05:05 UTC, drreynolds commented on src/idas/idas.c
> +                        MSG_RTFUNC_FAILED);
```suggestion
                        MSG_RTFUNC_FAILED, IDA_mem->ida_tlo);
```

2023-12-07 05:06 UTC, drreynolds commented on src/idas/idas.c
> +    IDAProcessError(IDA_mem, IDA_BAD_T, __LINE__, __func__, __FILE__, MSG_BAD_T);
```suggestion
    IDAProcessError(IDA_mem, IDA_BAD_T, __LINE__, __func__, __FILE__, MSG_BAD_T, t,
                    IDA_mem->ida_tn - IDA_mem->ida_hused, IDA_mem->ida_tn);
```

2023-12-07 05:06 UTC, drreynolds commented on src/idas/idas.c
> +    IDAProcessError(IDA_mem, IDA_BAD_T, __LINE__, __func__, __FILE__, MSG_BAD_T);
```suggestion
    IDAProcessError(IDA_mem, IDA_BAD_T, __LINE__, __func__, __FILE__, MSG_BAD_T, t,
                    IDA_mem->ida_tn - IDA_mem->ida_hused, IDA_mem->ida_tn);
```

2023-12-07 05:07 UTC, drreynolds commented on src/idas/idas.c
> +    IDAProcessError(IDA_mem, IDA_BAD_T, __LINE__, __func__, __FILE__, MSG_BAD_T);
```suggestion
    IDAProcessError(IDA_mem, IDA_BAD_T, __LINE__, __func__, __FILE__, MSG_BAD_T,
                    t, IDA_mem->ida_tn - IDA_mem->ida_hused, IDA_mem->ida_tn);
```

2023-12-07 05:07 UTC, drreynolds commented on src/idas/idas.c
> +                      MSG_BAD_TSTOP);
```suggestion
                      MSG_BAD_TSTOP, IDA_mem->ida_tstop, IDA_mem->ida_tn);
```

2023-12-07 05:08 UTC, drreynolds commented on src/idas/idas.c
> +                          MSG_BAD_TSTOP);
```suggestion
                          MSG_BAD_TSTOP, IDA_mem->ida_tstop, IDA_mem->ida_tn);
```

2023-12-07 05:08 UTC, drreynolds commented on src/idas/idas.c
> +                        MSG_BAD_TOUT);
```suggestion
                        MSG_BAD_TOUT, tout);
```

2023-12-07 05:08 UTC, drreynolds commented on src/idas/idas.c
> +                    MSG_ERR_FAILS);
```suggestion
                    MSG_ERR_FAILS, IDA_mem->ida_tn, IDA_mem->ida_hh);
```

2023-12-07 05:08 UTC, drreynolds commented on src/idas/idas.c
> +                    MSG_CONV_FAILS);
```suggestion
                    MSG_CONV_FAILS, IDA_mem->ida_tn, IDA_mem->ida_hh);
```

2023-12-07 05:09 UTC, drreynolds commented on src/idas/idas.c
> +                    MSG_SETUP_FAILED);
```suggestion
                    MSG_SETUP_FAILED, IDA_mem->ida_tn);
```

2023-12-07 05:09 UTC, drreynolds commented on src/idas/idas.c
> +                    MSG_SOLVE_FAILED);
```suggestion
                    MSG_SOLVE_FAILED, IDA_mem->ida_tn);
```

2023-12-07 05:09 UTC, drreynolds commented on src/idas/idas.c
> +                    MSG_REP_RES_ERR);
```suggestion
                    MSG_REP_RES_ERR, IDA_mem->ida_tn);
```

2023-12-07 05:09 UTC, drreynolds commented on src/idas/idas.c
> +                    MSG_RES_NONRECOV);
```suggestion
                    MSG_RES_NONRECOV, IDA_mem->ida_tn);
```

2023-12-07 05:10 UTC, drreynolds commented on src/idas/idas.c
> +                    MSG_QRHSFUNC_REPTD);
```suggestion
                    MSG_QRHSFUNC_REPTD, IDA_mem->ida_tn);
```

2023-12-07 05:10 UTC, drreynolds commented on src/idas/idas.c
> +                    MSG_QRHSFUNC_FAILED);
```suggestion
                    MSG_QRHSFUNC_FAILED, IDA_mem->ida_tn);
```

2023-12-07 05:10 UTC, drreynolds commented on src/idas/idas.c
> +                    MSG_SRES_REPTD);
```suggestion
                    MSG_SRES_REPTD, IDA_mem->ida_tn);
```

2023-12-07 05:10 UTC, drreynolds commented on src/idas/idas.c
> +                    MSG_SRES_FAILED);
```suggestion
                    MSG_SRES_FAILED, IDA_mem->ida_tn);
```

2023-12-07 05:10 UTC, drreynolds commented on src/idas/idas.c
> +                    MSG_QSRHSFUNC_REPTD);
```suggestion
                    MSG_QSRHSFUNC_REPTD, IDA_mem->ida_tn);
```

2023-12-07 05:11 UTC, drreynolds commented on src/idas/idas.c
> +                    MSG_QSRHSFUNC_FAILED);
```suggestion
                    MSG_QSRHSFUNC_FAILED, IDA_mem->ida_tn);
```

2023-12-07 05:11 UTC, drreynolds commented on src/idas/idas.c
> +                    MSG_FAILED_CONSTR);
```suggestion
                    MSG_FAILED_CONSTR, IDA_mem->ida_tn);
```

2023-12-07 05:11 UTC, drreynolds commented on src/idas/idas.c
> +                    MSG_NLS_INPUT_NULL);
```suggestion
                    MSG_NLS_INPUT_NULL, IDA_mem->ida_tn);
```

2023-12-07 05:11 UTC, drreynolds commented on src/idas/idas.c
> +                    MSG_NLS_SETUP_FAILED);
```suggestion
                    MSG_NLS_SETUP_FAILED, IDA_mem->ida_tn);
```

2023-12-07 05:11 UTC, drreynolds commented on src/idas/idas.c
> +                    MSG_NLS_FAIL);
```suggestion
                    MSG_NLS_FAIL, IDA_mem->ida_tn);
```

2023-12-07 05:12 UTC, drreynolds commented on src/idas/idas.c
> +    IDAProcessError(IDA_mem, IDA_BAD_T, __LINE__, __func__, __FILE__, MSG_BAD_T);
```suggestion
    IDAProcessError(IDA_mem, IDA_BAD_T, __LINE__, __func__, __FILE__, MSG_BAD_T, t,
                    IDA_mem->ida_tn - IDA_mem->ida_hused, IDA_mem->ida_tn);
```

2023-12-07 05:12 UTC, drreynolds commented on src/idas/idas.c
> +     (msgfmt is the last required argument to cvProcessError) */
```suggestion
     (msgfmt is the last required argument to IDAProcessError) */
```

2023-12-07 05:13 UTC, drreynolds commented on src/idas/idas_impl.h
> +
```suggestion
```

2023-12-07 05:14 UTC, drreynolds commented on src/idas/idas_io.c
> +                      MSG_BAD_TSTOP);
```suggestion
                      MSG_BAD_TSTOP, tstop, IDA_mem->ida_tn);
```

2023-12-07 05:16 UTC, drreynolds commented on src/idas/idas_ls.c
> +                    MSG_LS_CFN_WARN);
```suggestion
                    MSG_LS_CFN_WARN, IDA_mem->ida_tn, rcfn);
```

2023-12-07 05:16 UTC, drreynolds commented on src/idas/idas_ls.c
> +                    MSG_LS_CFL_WARN);
```suggestion
                    MSG_LS_CFL_WARN, IDA_mem->ida_tn, rcfn);
```

2023-12-08 19:25 UTC, drreynolds approved these changes

2023-12-09 01:07 UTC, gardner48 requested changes
Also noticed IDAS does not have an error handler unit test like CVODE and ARKODE

2023-12-09 01:07 UTC, gardner48 commented on src/idas/idas_ls.c
> -    IDAProcessError(NULL, IDALS_MEM_NULL, "IDASLS", fname, MSG_LS_IDAMEM_NULL);
`fname` could be removed as an input to `idaLs_AccessLMemB`

2023-12-09 01:07 UTC, gardner48 commented on src/idas/idas_ls.c
> -    IDAProcessError(NULL, IDALS_MEM_NULL, "IDASLS", fname, MSG_LS_IDAMEM_NULL);
`fname` could be removed as an input to `idaLs_AccessLMem`

2023-12-09 01:07 UTC, gardner48 commented on src/idas/idas_ls.c
> -    IDAProcessError(NULL, IDALS_MEM_NULL, "IDASLS", fname, MSG_LS_IDAMEM_NULL);
`fname` could be removed as an input to `idaLs_AccessLMemBCur`

2023-12-12 22:57 UTC, gardner48 requested changes

2023-12-12 22:57 UTC, gardner48 commented on doc/idas/guide/source/Usage/SIM.rst
There are some occurrences of `IDASetErrFile` in 

* `doc/idas/guide/source/Usage/FSA.rst`
* `doc/idas/guide/source/Usage/SIM.rst`

and `IDASetErrHandlerFn` in 

* `doc/idas/guide/source/Usage/SIM.rst`

2023-12-12 22:57 UTC, gardner48 commented on src/idas/idas.c
> +#if SUNDIALS_LOGGING_LEVEL >= 1
```suggestion
#if SUNDIALS_LOGGING_LEVEL >= SUNDIALS_LOGGING_WARNING
```

2023-12-12 22:57 UTC, gardner48 commented on test/unit_tests/idas/gtest/CMakeLists.txt
> +add_dependencies(test_idas_error_handling sundials_ida_obj)
```suggestion
add_dependencies(test_idas_error_handling sundials_idas_obj)
```

2023-12-12 23:56 UTC, balos1 commented on test/unit_tests/idas/gtest/CMakeLists.txt
> +gtest_discover_tests(test_idas_error_handling)
```suggestion
gtest_discover_tests(test_idas_error_handling)

```

2023-12-13 00:15 UTC, gardner48 approved these changes

2023-12-13 03:31 UTC, merged