error handling in ida
LLNL/sundials pull request #385
Opened 2023-12-06 22:42 UTC by balos1

2023-12-07 04:23 UTC, drreynolds requested changes

2023-12-07 04:23 UTC, drreynolds commented on src/ida/ida.c
> +                    MSG_SOLVE_FAILED);
```suggestion
                    MSG_SOLVE_FAILED, IDA_mem->ida_tn);
```

2023-12-07 04:23 UTC, drreynolds commented on src/ida/ida.c
> +                    MSG_NLS_INPUT_NULL);
```suggestion
                    MSG_NLS_INPUT_NULL, IDA_mem->ida_tn);
```

2023-12-07 04:23 UTC, drreynolds commented on src/ida/ida.c
> +                    MSG_NLS_SETUP_FAILED);
```suggestion
                    MSG_NLS_SETUP_FAILED, IDA_mem->ida_tn);
```

2023-12-07 04:23 UTC, drreynolds commented on src/ida/ida.c
> +    IDAProcessError(IDA_mem, IDA_BAD_T, __LINE__, __func__, __FILE__, MSG_BAD_T);
```suggestion
    IDAProcessError(IDA_mem, IDA_BAD_T, __LINE__, __func__, __FILE__, MSG_BAD_T, t,
                    IDA_mem->ida_tn - IDA_mem->ida_hused, IDA_mem->ida_tn);
```

2023-12-07 04:23 UTC, drreynolds commented on src/ida/ida.c
> +     (msgfmt is the last required argument to cvProcessError) */
```suggestion
     (msgfmt is the last required argument to IDAProcessError) */
```

2023-12-07 04:23 UTC, drreynolds commented on src/ida/ida_io.c
> +                      MSG_BAD_TSTOP);
```suggestion
                      MSG_BAD_TSTOP, tstop, IDA_mem->ida_tn);
```

2023-12-08 03:37 UTC, drreynolds approved these changes
Minor commenting error, otherwise this looks good.

2023-12-08 03:37 UTC, drreynolds commented on src/ida/ida.c
> +     (msgfmt is the last required argument to cvProcessError) */
```suggestion
     (msgfmt is the last required argument to IDAProcessError) */
```

2023-12-09 01:20 UTC, gardner48 requested changes
Also noticed IDAS does not have an error handler unit test like CVODE and ARKODE

2023-12-09 01:20 UTC, gardner48 commented on doc/ida/guide/source/Introduction.rst
> +Users of these functions should use the :c:type:`SUNLogger` API instead.
Same comment as in the ARKODE PR.

2023-12-09 01:20 UTC, gardner48 commented on doc/ida/guide/source/Usage/index.rst
> -.. c:function:: int IDASetErrFile(void * ida_mem, FILE * errfp)
Looks like there are still some instances of `IDASetErrFile` and `IDASetErrHandlerFn` elsewhere in this file. Also need to remove `IDAErrHandlerFn` documentation.

2023-12-09 01:20 UTC, gardner48 commented on include/ida/ida.h
> -SUNDIALS_EXPORT int IDASetErrHandlerFn(void* ida_mem, IDAErrHandlerFn ehfun,
Remove `IDAErrHandlerFn` above

2023-12-09 01:20 UTC, gardner48 commented on src/ida/ida.c
> -  if (error_code == IDA_WARNING) { sprintf(err_type, "WARNING"); }
There are couple uses of `IDAProcessError` where the message is intended to be a warning rather than an error.

2023-12-09 01:20 UTC, gardner48 commented on src/ida/ida_ls.c
> -    IDAProcessError(NULL, IDALS_MEM_NULL, "IDALS", fname, MSG_LS_IDAMEM_NULL);
`fname` could be removed as an input to `idaLs_AccessLMem`

2023-12-12 23:20 UTC, gardner48 requested changes

2023-12-12 23:20 UTC, gardner48 commented on src/ida/ida.c
> +#if SUNDIALS_LOGGING_LEVEL >= 1
```suggestion
#if SUNDIALS_LOGGING_LEVEL >= SUNDIALS_LOGGING_WARNING
```

2023-12-13 00:15 UTC, gardner48 approved these changes

2023-12-13 02:18 UTC, drreynolds approved these changes

2023-12-13 03:32 UTC, merged