error handling in kinsol
LLNL/sundials pull request #386
Opened 2023-12-06 22:42 UTC by balos1

2023-12-07 04:50 UTC, drreynolds requested changes

2023-12-07 04:50 UTC, drreynolds commented on src/kinsol/kinsol.c
> +     (msgfmt is the last required argument to cvProcessError) */
```suggestion
     (msgfmt is the last required argument to KINProcessError) */
```

2023-12-09 01:34 UTC, gardner48 requested changes
Also noticed KINSOL does not have an error handler unit test like CVODE and ARKODE

2023-12-09 01:34 UTC, gardner48 commented on doc/kinsol/guide/source/Introduction.rst
> +Users of these functions should use the :c:type:`SUNLogger` API instead.
Similar comment as in the ARKODE PR.

2023-12-09 01:34 UTC, gardner48 commented on doc/kinsol/guide/source/Usage/index.rst
> -.. c:function:: int KINSetErrFile(void * kin_mem, FILE * errfp)
Looks like there are still some instances of `KINSetErrFile` and `KINSetErrHandlerFn` elsewhere in this file

2023-12-09 01:34 UTC, gardner48 commented on src/kinsol/kinsol.c
> -  if (error_code == KIN_WARNING) { sprintf(err_type, "WARNING"); }
Unlike the other packages, I don't see any cases where KINSOL issues warnings.

2023-12-09 01:34 UTC, gardner48 commented on src/kinsol/kinsol_ls.c
> -    KINProcessError(NULL, KINLS_MEM_NULL, "KINLS", fname, MSG_LS_KINMEM_NULL);
`fname` could be removed as an input to `kinLs_AccessLMem`

2023-12-12 15:18 UTC, drreynolds approved these changes

2023-12-12 23:27 UTC, gardner48 requested changes

2023-12-12 23:27 UTC, gardner48 commented on src/kinsol/kinsol.c
> +#if SUNDIALS_LOGGING_LEVEL >= 1
```suggestion
#if SUNDIALS_LOGGING_LEVEL >= SUNDIALS_LOGGING_WARNING
```

2023-12-12 23:27 UTC, gardner48 commented on src/kinsol/kinsol_io.c
> +    KINProcessError(kin_mem, KIN_ILL_INPUT, __LINE__, __func__, __FILE__,
Good catch here and above!

2023-12-13 00:16 UTC, gardner48 approved these changes

2023-12-13 02:11 UTC, drreynolds approved these changes

2023-12-13 03:32 UTC, merged