Release/v6.7.0
LLNL/sundials pull request #399
Opened 2023-12-16 00:34 UTC by balos1

2023-12-16 03:36 UTC, drreynolds submitted a review, later dismissed

2023-12-18 08:37 UTC, gardner48 requested changes
The change log needs to be corrected (some items in 6.7.0 are listed under 6.6.1). I'll push up an updated log shortly.

2023-12-18 11:08 UTC, gardner48 commented
I've updated the change log but noticed this PR includes a merge commit with `main`. It Iooks like this release branch was made from `develop` with some later commits on `develop` cherry-picked over. To avoid the merge commit, I've made another branch we could use, `release/6.7.0` (does not have `v` in the version number), from `main` with all the same `develop` history in this PR cherry-picked. 

In case we want to use this branch, I've opened a draft PR for it to get the CI going.

2023-12-18 15:57 UTC, balos1 commented
@gardner48 I rebased this branch and removed the merged commit

2023-12-18 16:01 UTC, closed without merging