remove explicit default destructor from core classes
LLNL/sundials pull request #413
Opened 2024-02-05 23:05 UTC by balos1

Fixes https://github.com/LLNL/sundials/issues/329

2024-02-05 23:14 UTC, drreynolds submitted a review, later dismissed

2024-02-06 16:18 UTC, gardner48 requested changes
Was providing the default constructor unnecessary before?
Need to update the change log to note the bug fix for C++20 users.

2024-02-06 16:47 UTC, balos1 commented
Yes, it seems it was unnecessary before.

2024-02-07 19:21 UTC, gardner48 approved these changes

2024-02-07 19:59 UTC, merged