F2003 examples
LLNL/sundials pull request #420
Opened 2024-02-08 19:06 UTC by drreynolds

This PR replaces #302, since it proved way too difficult to merge changes from `develop` directly into that branch, so I just propagated the new/changed files from #302 into a new branch off of `develop`.

2024-02-13 18:48 UTC, balos1 requested changes
This looks good. Ill handle the CMake template update.

2024-02-13 19:24 UTC, drreynolds commented on examples/arkode/F2003_parallel/ark_diag_kry_bbd_f2003.f90
> +     ! Print some final statistics
I agree that it would be good to add calls to those statistics output functions for all SUNDIALS examples (in a future PR).

2024-02-13 19:48 UTC, drreynolds commented on examples/kinsol/F2003_parallel/CMakeLists.txt
> +if(MPI_Fortran_COMPILER)
Turns out that the block was needed, but perhaps your suggestion of adding `MPI::MPI_Fortran` to the `target_link_libraries` will work...

2024-02-17 01:30 UTC, balos1 commented on examples/templates/cmakelists_openmp_F2003_ex.in
This can be done later on, when #304 gets revived.

2024-02-17 01:30 UTC, balos1 approved these changes

2024-02-21 18:13 UTC, merged