Update sundials_hip_policies.hpp to account for "amd" HIP_PLATFORM
LLNL/sundials pull request #434
Opened 2024-03-06 23:42 UTC by ashesh2512

With newer versions of rocm, specifically 6.0.0, we have observed that the environment variable HIP_PLATFORM needs to be "amd". As a consequence, the WARP_SIZE goes undefined. I have spoken with AMD personnel, and they too suggest setting HIP_PLATFORM=AMD.

2024-03-08 21:45 UTC, gardner48 requested changes
@ashesh2512 Thank you for reporting this issue and providing a fix. [ROCm 6.0.0 removed](https://rocm.docs.amd.com/en/latest/about/CHANGELOG.html#id5) both `__HIP_PLATFORM_HCC__` and `__HIP_PLATFORM_NVCC__`.

In addition to updating the `#elif` case, please target the `develop` branch with your PR and sign your last commit as indicated in the [Contributing guide](https://github.com/LLNL/sundials/blob/main/CONTRIBUTING.md).

2024-03-08 21:45 UTC, gardner48 commented on include/sundials/sundials_hip_policies.hpp
>  #elif defined(__HIP_PLATFORM_NVCC__)
```suggestion
#elif defined(__HIP_PLATFORM_NVCC__) || defined(__HIP_PLATFORM_NVDIA__)
```

2024-03-12 20:11 UTC, ashesh2512 commented
@gardner48 I have amended the message to the last commit.

2024-03-12 20:14 UTC, gardner48 approved these changes

2024-03-12 22:48 UTC, merged