Docs: Updating landing page, remove file tree figure
LLNL/sundials pull request #450
Opened 2024-03-27 19:06 UTC by gardner48

* Move high level description of SUNDIALS to docs landing page
* Remove file tree figure from docs (addresses #443)

2024-03-27 19:48 UTC, drreynolds submitted a review, later dismissed

2024-03-27 23:16 UTC, balos1 requested changes

2024-03-27 23:16 UTC, balos1 commented on doc/superbuild/source/Organization_link.rst
Removing this makes it so that the overall SUNDIALS organization figure `sunorg1.png` is not included anywhere in the superbuild for the HTML docs (only in the PDF docs for the individual packages).   You would need to remove the `ifconfig` [here](https://github.com/LLNL/sundials/blob/main/doc/arkode/guide/source/Organization.rst?plain=1#L21) (and in the corresponding places in the other package docs), but then the organization figure would be repeated for each package in the HTML build. So maybe we should keep this file? If not, you need to remove it from `doc/superbuild/source/index.rst`.

2024-03-28 00:18 UTC, gardner48 commented on doc/superbuild/source/Organization_link.rst
I've moved `sunorg1.png` so it appears at the start of the "Using SUNDIALS" chapter in all versions.

2024-03-28 04:51 UTC, balos1 requested changes

2024-03-28 04:51 UTC, balos1 commented on doc/arkode/guide/source/sundials/index.rst
> +.. _Organization.Sundials.HighLevelDiagram:
After previewing the docs, I think it might be better to have the figure at the bottom of the page.

2024-03-28 13:56 UTC, balos1 approved these changes

2024-03-28 13:56 UTC, merged