Add missing ark_mem frees if step mem malloc fails
LLNL/sundials pull request #453
Opened 2024-03-30 00:20 UTC by Steven-Roberts

2024-03-30 00:39 UTC, Steven-Roberts commented
These missing frees were pretty benign since they only caused memory leaks for certain "create" function errors. To find these sneaky issues more systematically we might need a static analysis tool.

2024-03-31 16:13 UTC, gardner48 requested changes

2024-03-31 16:13 UTC, gardner48 commented on src/arkode/arkode.c
> +    free(ark_mem);
```suggestion
    arkFree((void**)&ark_mem);
```

2024-03-31 16:13 UTC, gardner48 commented on src/arkode/arkode.c
> +    free(ark_mem);
```suggestion
    arkFree((void**)&ark_mem);
```

2024-03-31 16:13 UTC, gardner48 commented on src/arkode/arkode.c
> +    free(ark_mem);
```suggestion
    arkFree((void**)&ark_mem);
```

2024-03-31 16:27 UTC, gardner48 approved these changes

2024-03-31 19:31 UTC, merged