Make MRI step fail when inner stepper has a recoverable error
LLNL/sundials pull request #456
Opened 2024-04-16 21:36 UTC by Steven-Roberts

Fixes a bug where an MRI method would use the (likely corrupted) result of an inner stepper which returned with a recoverable error. Once adaptivity is supported, this could be handled similarly to ARK methods.

2024-04-16 21:37 UTC, gardner48 requested changes
Looks good, please update the change logs to note the fix

2024-04-16 22:39 UTC, gardner48 approved these changes

2024-04-17 01:58 UTC, drreynolds approved these changes

2024-04-17 04:33 UTC, gardner48 approved these changes

2024-04-17 14:16 UTC, merged