CMake: Fix dll install location
LLNL/sundials pull request #475
Opened 2024-05-14 14:44 UTC by jschueller

2024-05-15 12:19 UTC, mmuetzel commented
The same issue is solved slightly differently with a patch in MSYS2:
https://github.com/msys2/MINGW-packages/blob/8ff52af093c2d67d665e147d79049819e902e2bb/mingw-w64-sundials/0003-sundials-use-default-installdirs.patch

But admittedly, I prefer your proposed change.
Looks good to me. 👍

2024-05-15 12:24 UTC, jschueller commented
didnt know that you could omit DESTINATION like that, but that's only since cmake 3.14

2024-05-15 17:31 UTC, balos1 requested changes
Just a couple request w.r.t. the change notes. Please also sign your commit as per our [Contributing guide](https://github.com/LLNL/sundials/blob/main/CONTRIBUTING.md).

2024-05-15 17:31 UTC, balos1 commented on CHANGELOG.md
> +Fixed the runtime library installation path for windows systems. This fix changes the
```suggestion
Fixed the runtime library installation path for windows systems. This fix changes the 
default library installation path from `CMAKE_INSTALL_PREFIX/CMAKE_INSTALL_LIBDIR` to
`CMAKE_INSTALL_PREFIX/CMAKE_INSTALL_BINDIR`.
```

2024-05-15 17:31 UTC, balos1 commented on CHANGELOG.md
> +Fixed the runtime library installation path for windows systems. This fix changes the
Markdown formatting should use single backticks for inline code. Please also add this to `docs/shared/RecentChanges.rst` as well (which expects the double backticks).

2024-05-15 17:33 UTC, balos1 commented on CHANGELOG.md
> +``CMAKE_INSTALL_PREFIX/CMAKE_INSTALL_BINDIR``.
```suggestion
`CMAKE_INSTALL_PREFIX/CMAKE_INSTALL_BINDIR`.
```

2024-05-15 17:45 UTC, jschueller commented on CHANGELOG.md
> +Fixed the runtime library installation path for windows systems. This fix changes the
ok

2024-05-16 22:52 UTC, balos1 approved these changes

2024-05-17 03:57 UTC, merged