Maintenance/rename ginkgo dpcpp to sycl
LLNL/sundials pull request #493
Opened 2024-05-21 23:15 UTC by balos1

Ginkgo now refers to DPC++ as SYCL (inline with what Intel is doing), so this just updates our interface to match the naming convention.

2024-05-21 23:16 UTC, balos1 commented
Note that we will need to update our Spack package to handle this change.

2024-05-22 00:23 UTC, gardner48 requested changes
Minor doc items, otherwise this looks good

2024-05-22 00:23 UTC, gardner48 commented on doc/shared/RecentChanges.rst
> +Renamed the DPCPP value for the :cmakeop:`SUNDIALS_GINKGO_BACKENDS` CMake option to `SYCL` to match Ginkgo's updated naming convention.
```suggestion
Renamed the DPCPP value for the :cmakeop:`SUNDIALS_GINKGO_BACKENDS` CMake option to ``SYCL`` to match Ginkgo's updated naming convention.
```

2024-05-22 00:23 UTC, gardner48 commented on doc/shared/sundials/Install.rst
>     Default: "REF;OMP"
```suggestion
   Default: "REF;OMP"

   .. versionchanged: x.y.z 

      The ``DPCPP`` option was changed to ``SYCL`` to align with Ginkgo's naming convention.
```

2024-05-22 01:10 UTC, drreynolds approved these changes

2024-05-23 16:57 UTC, gardner48 approved these changes

2024-05-23 22:53 UTC, gardner48 approved these changes

2024-05-24 12:31 UTC, merged