Release/7.1.1
LLNL/sundials pull request #529
Opened 2024-06-25 15:58 UTC by balos1

2024-06-25 16:44 UTC, gardner48 requested changes

2024-06-25 16:44 UTC, gardner48 commented on CHANGELOG.md
>  ### Major Features
Remove the empty subsections under `7.1.1` here and in the recent changes file

2024-06-25 16:46 UTC, drreynolds submitted a review, later dismissed

2024-06-26 16:46 UTC, gardner48 approved these changes

2024-06-26 16:46 UTC, merged