README Updates
LLNL/sundials pull request #550
Opened 2024-08-01 04:30 UTC by Steven-Roberts

View of the rendered markdown: https://github.com/LLNL/sundials/blob/maintenance/readme/README.md

2024-08-01 16:57 UTC, drreynolds submitted a review, later dismissed

2024-08-02 16:12 UTC, gardner48 requested changes

2024-08-02 16:12 UTC, gardner48 commented on README.md
>  Full user guides for all of the SUNDIALS packages are available [online](https://sundials.readthedocs.io)
```suggestion
Full user guides for all of the SUNDIALS packages are available [online](https://sundials.readthedocs.io).
```

2024-08-02 16:12 UTC, gardner48 commented on README.md
> +example programs.
```suggestion
In the [released tarballs](https://github.com/LLNL/sundials/releases), the `doc` directory includes PDFs of the user guides and documentation for the example programs. The example program documentation PDFs are also available on the [releases page](https://github.com/LLNL/sundials/releases).
```

2024-08-02 21:45 UTC, gardner48 approved these changes

2024-08-05 16:20 UTC, balos1 approved these changes

2024-08-05 16:20 UTC, merged