Make hscale=0 for ARKodeResize consistent with docs
LLNL/sundials pull request #571
Opened 2024-09-11 23:23 UTC by Steven-Roberts

The [docs](https://sundials.readthedocs.io/en/latest/arkode/Usage/User_callable.html#arkode-system-resize-function) state

> If a value hscale<=0 is specified, the default of 1.0 will be used

2024-09-11 23:28 UTC, gardner48 requested changes

2024-09-11 23:28 UTC, gardner48 commented on src/arkode/arkode.c
> +  if (hscale <= ZERO) { hscale = ONE; }
Note the bugfix in the recent changes otherwise this looks good

2024-09-12 16:32 UTC, gardner48 approved these changes

2024-09-12 17:14 UTC, balos1 approved these changes

2024-09-12 18:40 UTC, merged